language: php


matrix:
  fast_finish: true
  include:
  - php: 7.3
  - php: 7.2
    sudo: true
    dist: trusty
    group: edge
    services:
      - redis-server
    cache:
      directories: "$HOME/.composer/cache"
    before_install:
    - wget https://phar.phpunit.de/phpunit-4.5.1.phar
    script:
    - php phpunit-4.5.1.phar --verbose $PHPUNIT_FLAGS

sudo: false

services:
  - redis-server

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.bin

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      PHPUNIT_FLAGS="--coverage-clover=clover.xml"
    else
      phpenv config-rm xdebug.ini || return 0
    fi

script:
  - ./vendor/bin/phpunit --verbose $PHPUNIT_FLAGS
